version: '3.3'
services:
  fibberbot:
    image: 'mrlicorice/fibberbot:latest'
    container_name: fibberbot
    build:
      context: ./app
      dockerfile: Dockerfile
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - './app:/app'
      - './config:/config'
      - './db:/db:rw'
    #ports:
    #  - '9022:22' # Expose port for SSH access
